### PR TITLE
feat: Get portfolio balance by PID and duration

### PR DESCRIPTION
**Pull request by julianooii**
# Get Portfolio Balance
End point to get sum of total balance of a single portfolio based on the quantity of assets in the portfolio for each day, calculated using adjusted close price.

## Steps
Send a GET request to the endpoint http://127.0.0.1:8080/api/portfolio/balance?duration=7&pid=1

## Expected Outcome
Json response will be returned.
- Key is Epoch time : Value is balance at given day
- Note that output in the example is limited due to the SQL data
- 0.0 indicates a weekend ( @jeromeandrewong Do you want me to remove or fill it with prev day balance? )
```json
{
    "dailyBalance": {
        "1698336000": 894.18,
        "1698422400": 0.0,
        "1698508800": 0.0,
        "1698595200": 4619.69,
        "1698681600": 4636.84,
        "1698768000": 4740.71,
        "1698854400": 4788.88,
        "1698940800": 8461.84,
        "1699027200": 0.0,
        "1699113600": 0.0
    }
}
```

## Validation
epoch 1698336000 corresponds to October 27, 2023
In SQL Table, at this date, we have 7 AMZN
At this date, AMZN closed at 127.74 -> Hence balance $894.18
image

### CODE REVIEW

**Comment by jeromeandrewong** [comment]
@julianooiii think weekend balance should not be zero, the balance of a portfolio would not be zero just because there are no trading activities on the weekend. i think we can fill with previous day balance

**Comment by julianooii** [comment]
@jeromeandrewong Done! this is the new output

```json
{
    "dailyBalance": {
        "1698336000": 894.18,
        "1698422400": 894.18,
        "1698508800": 894.18,
        "1698595200": 4619.69,
        "1698681600": 4636.84,
        "1698768000": 4740.71,
        "1698854400": 4788.88,
        "1698940800": 8461.84,
        "1699027200": 8461.84,
        "1699113600": 8461.84
    }
}
```

**Comment by julianooii** [comment]
@jeromeandrewong Done with the suggested changes and made some fixes. 

Expected Json output

```json
{
    "dailyBalance": {
        "1698336000": 894.18,
        "1698422400": 894.18,
        "1698508800": 894.18,
        "1698595200": 4619.69,
        "1698681600": 4636.84,
        "1698768000": 4740.71,
        "1698854400": 4788.88
    }
}
```

**Comment by julianooii** [comment]
Updated the JSON response according to new format
```json
{
    "portfolioHistoryData": [
        {
            "date": "2023-10-30",
            "balance": 4619.69
        },
        {
            "date": "2023-10-31",
            "balance": 4636.84
        },
        {
            "date": "2023-11-01",
            "balance": 4740.71
        },
        {
            "date": "2023-11-02",
            "balance": 4788.88
        },
        {
            "date": "2023-11-03",
            "balance": 8461.84
        },
        {
            "date": "2023-11-04",
            "balance": 8461.84
        },
        {
            "date": "2023-11-05",
            "balance": 8461.84
        }
    ]
}
```

**Review by jeromeandrewong — APPROVED** [review]
LGTM!

**Pull request merged**
